name: Content APP CI

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run build --if-present

      - name: Run tests
        env:
          NODE_ENV: test
          DB_HOST: postgres
          DB_USERNAME: test
          DB_PASSWORD: test
          DB_NAME: test
          DB_PORT: 5432
          PORT: 5000
        run: npm run test