version: "3.8"

services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=DB_NAME
    ports:
      - '$DB_PORT:$DB_PORT'
    container_name: app_db
    volumes:
      - psql_data:/var/lib/postgresql/data
  app:
    depends_on:
      - postgresdb
    build: .
    restart: always
    env_file: .env
    ports:
      - 5000:$PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    links:
      - postgresdb
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local
  psql_data: